apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: instruqt-website
spec:
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: instruqt-website
    spec:
      containers:
      - name: instruqt-website
        imagePullPolicy: Always
        image: gcr.io/instruqt/website:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
