apiVersion: v1
kind: Service
metadata:
  name: instruqt-website
  labels:
    app: instruqt-website
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: instruqt-website
